### ISSUE TITLE
使用GO client 连接 JAVA SERVER时经常异常退出，是什么问题

### ISSUE THREAD

**Issue by jackleibest** [apache/dubbo-go#809] opened 2020-10-28 01:29 UTC
GO client程序运行时，经常异常闪退，请问这要怎么解决，下面是捕获到的异常
2020-10-28T08:48:39.634+0800    ^[[33mWARN^[[0m could not find the metadata service creator for metadataType: local, please check whether you have imported relative packages,
local - github.com/apache/dubbo-go/metadata/service/inmemory,
remote - github.com/apache/dubbo-go/metadata/service/remote
2020-10-28T08:50:02.123+0800    ^[[33mWARN^[[0m client{peer:127.0.0.1:20814} goroutine exit now.
2020-10-28T08:50:02.123+0800    ^[[33mWARN^[[0m client{peer:127.0.0.1:20814} goroutine exit now.
2020-10-28T09:06:03.723+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:25.523+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:25.623+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:25.823+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:40.924+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:41.223+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:41.223+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:53.323+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:55.423+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:06:57.223+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:10:24.723+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:10:50.923+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:11:10.723+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-10-28T09:11:24.823+0800    ^[[33mWARN^[[0m result err: client read timeout
panic: runtime error: index out of range [0] with length 0

goroutine 506 [running]:
github.com/apache/dubbo-go/remoting/getty.(*gettyRPCClientPool).get(0xc0012b8400, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/apache/dubbo-go@v1.5.3/remoting/getty/pool.go:380 +0x2f6
github.com/apache/dubbo-go/remoting/getty.(*gettyRPCClientPool).getGettyRpcClient(0xc0012b8400, 0xc001280548, 0xf, 0xc0053312f8, 0x439bb2, 0xd51ba0)
        /root/go/pkg/mod/github.com/apache/dubbo-go@v1.5.3/remoting/getty/pool.go:355 +0x2f
github.com/apache/dubbo-go/remoting/getty.(*Client).selectSession(0xc00013f1e0, 0xc001280548, 0xf, 0xc0013f3816, 0xc0013f38c8, 0x1, 0xc0013f3810, 0xc0053313a0)
        /root/go/pkg/mod/github.com/apache/dubbo-go@v1.5.3/remoting/getty/getty_client.go:208 +0x4a
github.com/apache/dubbo-go/remoting/getty.(*Client).Request(0xc00013f1e0, 0xc001c92340, 0x12a05f200, 0xc00450ae70, 0xc00450ae70, 0xc001280548)
        /root/go/pkg/mod/github.com/apache/dubbo-go@v1.5.3/remoting/getty/getty_client.go:181 +0x51
github.com/apache/dubbo-go/remoting.(*ExchangeClient).Request(0xc0012d0a80, 0xc004154230, 0xc001280540, 0x5, 0xc001280548, 0xf, 0xc001280548, 0x9, 0xc001280552, 0x5, ...)
        /root/go/pkg/mod/github.com/apache/dubbo-go@v1.5.3/remoting/exchange_client.go:120 +0x347
github.com/apache/dubbo-go/protocol/dubbo.(*DubboInvoker).Invoke(0xc0005342a0, 0xf6b720, 0xc000038090, 0xf72c20, 0xc004cc18c0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/apache/dubbo-go@v1.5.3/protocol/dubbo/dubbo_invoker.go:137 +0xa70
github.com/apache/dubbo-go/common/proxy.(*Proxy).Implement.func1.1(0xc0023926e0, 0x3, 0x3, 0xc0023926e0, 0xb6506c, 0xc0013dd770)
        /root/go/pkg/mod/github.com/apache/dubbo-go@v1.5.3/common/proxy/proxy.go:161 +0x556
reflect.callReflect(0xc00051e690, 0xc005331fa0, 0xc005331f88)
        /usr/local/go/src/reflect/value.go:564 +0x32a
reflect.makeFuncStub(0xf6b720, 0xc000038090, 0xc0028c29a0, 0x2, 0x2, 0x1767610, 0xea2970, 0xc002af95b8, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/asm_amd64.s:20 +0x42
created by plugin-dubbo.run.func1.5
        /root/lestream/plugin-dubbo/main.go:45 +0x126

**Comment by zouyx** [comment] 2020-10-28 15:17
1. can you provide dubbo's version?
2. have you restart provider service? if you have , reference : https://github.com/apache/dubbo-go/issues/804

**Comment by jackleibest** [comment] 2020-10-29 01:47
1. the java dubbo version is dubbo-spring-boot-starter 2.7.4.1, and the go client dubbo the latest version.
2. I havn't restart provider service or consume client, however the client just take down due to the above problem mentioned.
so, still don't know why it happen?

**Comment by wenxuwan** [comment] 2020-10-29 06:52
Hi, this issue should be caused by error logic in the code, i will raise an pr to fix it.

**Comment by zouyx** [comment] 2020-10-31 03:11
@jackleibest Could you help to test that PR?

**Comment by jackleibest** [comment] 2020-10-31 06:39
I have try the fix solution, but I still got the error:
2020-10-31T10:03:43.501+0800    ^[[33mWARN^[[0m could not find the metadata service creator for metadataType: local, please check whether you have imported relative packages,
local - github.com/apache/dubbo-go/metadata/service/inmemory,
remote - github.com/apache/dubbo-go/metadata/service/remote
2020-10-31T10:09:31.126+0800    ^[[33mWARN^[[0m (ZkProviderRegistry)reconnectZkRegistry goroutine exit now...
2020-10-31T10:09:31.126+0800    ^[[33mWARN^[[0m client.done(), listen(path{/dubbo/com.huarui.stream.extern.ServiceProvider/providers}) goroutine exit now...
2020-10-31T10:09:31.126+0800    ^[[33mWARN^[[0m listenDirEvent(zkPath{/dubbo/com.huarui.stream.extern.ServiceProvider/providers}) goroutine exit now
2020-10-31T10:09:31.126+0800    ^[[33mWARN^[[0m listenSelf(zk path{/dubbo/com.huarui.stream.extern.ServiceProvider/providers/dubbo%3A%2F%2F10.7.73.47%3A20000%2FUserProvider%3Faccesslog%3D%26anyhost%3Dtrue%26app.version%3D0.0.1%26application%3DGoService%26auth%3D%26bean.name%3DUserProvider%26cluster%3Dfailover%26environment%3Drelease%26execute.limit%3D%26execute.limit.rejected.handler%3D%26group%3D%26interface%3Dcom.huarui.stream.extern.ServiceProvider%26ip%3D10.7.73.47%26loadbalance%3Drandom%26methods.CheckStreamStatus.loadbalance%3Drandom%26methods.CheckStreamStatus.retries%3D1%26methods.CheckStreamStatus.tps.limit.interval%3D%26methods.CheckStreamStatus.tps.limit.rate%3D%26methods.CheckStreamStatus.tps.limit.strategy%3D%26methods.CheckStreamStatus.weight%3D0%26methods.CreateStream.loadbalance%3Drandom%26methods.CreateStream.retries%3D3%26methods.CreateStream.tps.limit.interval%3D%26methods.CreateStream.tps.limit.rate%3D%26methods.CreateStream.tps.limit.strategy%3D%26methods.CreateStream.weight%3D0%26methods.StopStream.loadbalance%3Drandom%26methods.StopStream.retries%3D3%26methods.StopStream.tps.limit.interval%3D%26methods.StopStream.tps.limit.rate%3D%26methods.StopStream.tps.limit.strategy%3D%26methods.StopStream.weight%3D0%26module%3Ddubbogo%2Buser-info%2Bserver%26name%3DGoService%26organization%3Dikurento.com%26owner%3DZX%26param.sign%3D%26pid%3D46620%26registry.role%3D3%26release%3Ddubbo-golang-1.3.0%26retries%3D%26serialization%3D%26service.filter%3Decho%252Ctoken%252Caccesslog%252Ctps%252Cgeneric_service%252Cexecute%252Cpshutdown%26side%3Dprovider%26ssl-enabled%3Dfalse%26timestamp%3D1604109823%26tps.limit.interval%3D%26tps.limit.rate%3D%26tps.limit.rejected.handler%3D%26tps.limit.strategy%3D%26tps.limiter%3D%26version%3D%26warmup%3D100}) goroutine exit now
2020-10-31T10:09:31.126+0800    ^[[33mWARN^[[0m Selector.watch() = error{listener have been closed}
2020-10-31T10:09:31.127+0800    ^[[33mWARN^[[0m server{[::]:20000}.Accept() = err {accept tcp [::]:20000: use of closed network connection
github.com/apache/dubbo-getty.(*server).accept
        /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:239
github.com/apache/dubbo-getty.(*server).runTcpEventLoop.func1
        /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:273
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
github.com/apache/dubbo-getty.(*server).runTcpEventLoop.func1
        /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:286
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374}
2020-10-31T10:09:31.127+0800    ^[[33mWARN^[[0m server{[::]:20000} stop accepting client connect request.

**Comment by zouyx** [comment] 2020-11-02 07:34
> I have try the fix solution, but I still got the error:
> 2020-10-31T10:03:43.501+0800 ^[[33mWARN^[[0m could not find the metadata service creator for metadataType: local, please check whether you have imported relative packages,
> local - github.com/apache/dubbo-go/metadata/service/inmemory,
> remote - github.com/apache/dubbo-go/metadata/service/remote
> 2020-10-31T10:09:31.126+0800 ^[[33mWARN^[[0m (ZkProviderRegistry)reconnectZkRegistry goroutine exit now...
> 2020-10-31T10:09:31.126+0800 ^[[33mWARN^[[0m client.done(), listen(path{/dubbo/com.huarui.stream.extern.ServiceProvider/providers}) goroutine exit now...
> 2020-10-31T10:09:31.126+0800 ^[[33mWARN^[[0m listenDirEvent(zkPath{/dubbo/com.huarui.stream.extern.ServiceProvider/providers}) goroutine exit now
> 2020-10-31T10:09:31.126+0800 ^[[33mWARN^[[0m listenSelf(zk path{/dubbo/com.huarui.stream.extern.ServiceProvider/providers/dubbo%3A%2F%2F10.7.73.47%3A20000%2FUserProvider%3Faccesslog%3D%26anyhost%3Dtrue%26app.version%3D0.0.1%26application%3DGoService%26auth%3D%26bean.name%3DUserProvider%26cluster%3Dfailover%26environment%3Drelease%26execute.limit%3D%26execute.limit.rejected.handler%3D%26group%3D%26interface%3Dcom.huarui.stream.extern.ServiceProvider%26ip%3D10.7.73.47%26loadbalance%3Drandom%26methods.CheckStreamStatus.loadbalance%3Drandom%26methods.CheckStreamStatus.retries%3D1%26methods.CheckStreamStatus.tps.limit.interval%3D%26methods.CheckStreamStatus.tps.limit.rate%3D%26methods.CheckStreamStatus.tps.limit.strategy%3D%26methods.CheckStreamStatus.weight%3D0%26methods.CreateStream.loadbalance%3Drandom%26methods.CreateStream.retries%3D3%26methods.CreateStream.tps.limit.interval%3D%26methods.CreateStream.tps.limit.rate%3D%26methods.CreateStream.tps.limit.strategy%3D%26methods.CreateStream.weight%3D0%26methods.StopStream.loadbalance%3Drandom%26methods.StopStream.retries%3D3%26methods.StopStream.tps.limit.interval%3D%26methods.StopStream.tps.limit.rate%3D%26methods.StopStream.tps.limit.strategy%3D%26methods.StopStream.weight%3D0%26module%3Ddubbogo%2Buser-info%2Bserver%26name%3DGoService%26organization%3Dikurento.com%26owner%3DZX%26param.sign%3D%26pid%3D46620%26registry.role%3D3%26release%3Ddubbo-golang-1.3.0%26retries%3D%26serialization%3D%26service.filter%3Decho%252Ctoken%252Caccesslog%252Ctps%252Cgeneric_service%252Cexecute%252Cpshutdown%26side%3Dprovider%26ssl-enabled%3Dfalse%26timestamp%3D1604109823%26tps.limit.interval%3D%26tps.limit.rate%3D%26tps.limit.rejected.handler%3D%26tps.limit.strategy%3D%26tps.limiter%3D%26version%3D%26warmup%3D100}) goroutine exit now
> 2020-10-31T10:09:31.126+0800 ^[[33mWARN^[[0m Selector.watch() = error{listener have been closed}
> 2020-10-31T10:09:31.127+0800 ^[[33mWARN^[[0m server{[::]:20000}.Accept() = err {accept tcp [::]:20000: use of closed network connection
> github.com/apache/dubbo-getty.(*server).accept
> /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:239
> github.com/apache/dubbo-getty.(*server).runTcpEventLoop.func1
> /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:273
> runtime.goexit
> /usr/local/go/src/runtime/asm_amd64.s:1374
> github.com/apache/dubbo-getty.(*server).runTcpEventLoop.func1
> /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:286
> runtime.goexit
> /usr/local/go/src/runtime/asm_amd64.s:1374}
> 2020-10-31T10:09:31.127+0800 ^[[33mWARN^[[0m server{[::]:20000} stop accepting client connect request.

Are you use dubbo-go v1.5.4?

**Comment by jackleibest** [comment] 2020-11-02 07:44
dubbo-go@v1.5.3

**Comment by zouyx** [comment] 2020-11-02 08:48
> dubbo-go@v1.5.3

There is a problem in v1.5.3，so we release a bugfix version which is called [v1.5.4](https://github.com/apache/dubbo-go/releases/tag/v1.5.4)

**Comment by jackleibest** [comment] 2020-11-02 09:33
I have try the 1.5.4, however same with the old thing.

2020-11-02T16:46:21.372+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-11-02T16:46:43.372+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:14:127.0.0.1:34578<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 408, Read Pkgs: 0, Write Pkgs: 5} timeout{24.98972334s}, reqNum{0}
2020-11-02T16:46:48.373+0800    ^[[31mERROR^[[0m        client.getClientSession(session{session {client:TCP_CLIENT:14:127.0.0.1:34578<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 408, Read Pkgs: 0, Write Pkgs: 5}) = error{session not exist}
2020-11-02T16:46:48.672+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:15:127.0.0.1:34580<->127.0.0.1:20814}, Read Bytes: 17, Write Bytes: 85, Read Pkgs: 0, Write Pkgs: 5} timeout{24.999511372s}, reqNum{0}
2020-11-02T16:53:01.372+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-11-02T16:53:23.373+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:16:127.0.0.1:34742<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 408, Read Pkgs: 0, Write Pkgs: 5} timeout{24.988581494s}, reqNum{0}
2020-11-02T16:53:28.372+0800    ^[[31mERROR^[[0m        client.getClientSession(session{session {client:TCP_CLIENT:16:127.0.0.1:34742<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 408, Read Pkgs: 0, Write Pkgs: 5}) = error{session not exist}
2020-11-02T16:53:31.372+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-11-02T16:53:33.372+0800    ^[[31mERROR^[[0m        client.getClientSession(session{session {client:TCP_CLIENT:16:127.0.0.1:34742<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 408, Read Pkgs: 0, Write Pkgs: 5}) = error{session not exist}
2020-11-02T16:53:33.372+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:17:127.0.0.1:34744<->127.0.0.1:20814}, Read Bytes: 17, Write Bytes: 425, Read Pkgs: 0, Write Pkgs: 6} timeout{29.699862726s}, reqNum{0}
2020-11-02T16:53:46.372+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-11-02T16:54:08.372+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:18:127.0.0.1:34764<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 408, Read Pkgs: 0, Write Pkgs: 5} timeout{24.988568845s}, reqNum{0}
2020-11-02T16:54:13.372+0800    ^[[31mERROR^[[0m        client.getClientSession(session{session {client:TCP_CLIENT:18:127.0.0.1:34764<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 408, Read Pkgs: 0, Write Pkgs: 5}) = error{session not exist}
2020-11-02T16:54:13.672+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:19:127.0.0.1:34766<->127.0.0.1:20814}, Read Bytes: 17, Write Bytes: 85, Read Pkgs: 0, Write Pkgs: 5} timeout{24.999834027s}, reqNum{0}
2020-11-02T17:24:36.972+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-11-02T17:24:36.972+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-11-02T17:24:37.273+0800    ^[[33mWARN^[[0m result err: client read timeout
2020-11-02T17:24:58.972+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:20:127.0.0.1:35564<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 626, Read Pkgs: 0, Write Pkgs: 6} timeout{24.979803784s}, reqNum{0}
2020-11-02T17:24:59.272+0800    ^[[33mWARN^[[0m session{session {client:TCP_CLIENT:21:127.0.0.1:35568<->127.0.0.1:20814}, Read Bytes: 66, Write Bytes: 40925, Read Pkgs: 0, Write Pkgs: 5} timeout{24.990474477s}, reqNum{0}
2020-11-02T17:31:14.054+0800    ^[[33mWARN^[[0m (ZkProviderRegistry)reconnectZkRegistry goroutine exit now...
2020-11-02T17:31:14.054+0800    ^[[33mWARN^[[0m Selector.watch() = error{listener have been closed}
2020-11-02T17:31:14.054+0800    ^[[33mWARN^[[0m client.done(), listen(path{/dubbo/com.huarui.stream.extern.ServiceProvider/providers}) goroutine exit now...
2020-11-02T17:31:14.054+0800    ^[[33mWARN^[[0m listenDirEvent(zkPath{/dubbo/com.huarui.stream.extern.ServiceProvider/providers}) goroutine exit now
2020-11-02T17:31:14.054+0800    ^[[33mWARN^[[0m listenSelf(zk path{/dubbo/com.huarui.stream.extern.ServiceProvider/providers/dubbo%3A%2F%2F10.7.73.47%3A20000%2FUserProvider%3Fanyhost%3Dtrue%26app.version%3D0.0.1%26application%3DGoService%26bean.name%3DUserProvider%26cluster%3Dfailover%26environment%3Drelease%26interface%3Dcom.huarui.stream.extern.ServiceProvider%26ip%3D10.7.73.47%26loadbalance%3Drandom%26methods.CheckStreamStatus.loadbalance%3Drandom%26methods.CheckStreamStatus.retries%3D1%26methods.CheckStreamStatus.weight%3D0%26methods.CreateStream.loadbalance%3Drandom%26methods.CreateStream.retries%3D3%26methods.CreateStream.weight%3D0%26methods.StopStream.loadbalance%3Drandom%26methods.StopStream.retries%3D3%26methods.StopStream.weight%3D0%26module%3Ddubbogo+user-info+server%26name%3DGoService%26organization%3Dikurento.com%26owner%3DZX%26pid%3D810%26registry.role%3D3%26release%3Ddubbo-golang-1.3.0%26service.filter%3Decho%2Ctoken%2Caccesslog%2Ctps%2Cgeneric_service%2Cexecute%2Cpshutdown%26side%3Dprovider%26ssl-enabled%3Dfalse%26timestamp%3D1604303998%26warmup%3D100}) goroutine exit now
2020-11-02T17:31:14.057+0800    ^[[33mWARN^[[0m server{[::]:20000}.Accept() = err {accept tcp [::]:20000: use of closed network connection
github.com/apache/dubbo-getty.(*server).accept
        /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:239
github.com/apache/dubbo-getty.(*server).runTcpEventLoop.func1
        /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:273
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
github.com/apache/dubbo-getty.(*server).runTcpEventLoop.func1
        /root/go/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/server.go:286
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374}
2020-11-02T17:31:14.057+0800    ^[[33mWARN^[[0m server{[::]:20000} stop accepting client connect request.

**Comment by jackleibest** [comment] 2020-11-02 12:04
and, that's one more thing, my java dubbo provider is always online, it is never restart, but the go client just goes down

**Comment by AlexStocks** [comment] 2020-11-02 12:54
@jackleibest will u join in the DingDing Group 23331795 and then have a talk with us to fix this bug quickly?

**Comment by wenxuwan** [comment] 2020-11-05 06:19
@jackleibest can you provide logs on your provider side, from the log you have attached, your client read timeout always.

**Comment by jackleibest** [comment] 2020-11-05 06:22
sorry about that, due to the unstable connecting, we just decided to change the communications with websocket.

**Comment by wenxuwan** [comment] 2020-11-05 06:48
> sorry about that, due to the unstable connecting, we just decided to change the communications with websocket.

Ok, so do you know the reason of unstable connecting ?

**Comment by zouyx** [comment] 2020-12-17 02:23
If no another problems i will close this issue.

**Closed by zouyx** 2020-12-17 02:23 UTC
Labels: bug, help wanted
