### ISSUE TITLE
Dubbo-go condition routing rule

### ISSUE THREAD

**Issue by FinalT** [apache/dubbo-go#2269] opened 2023-03-27 08:54 UTC
Implement condition routing in Dubbo-go traffic control（实现dubbo-go流量管控中的条件路由）

Complete relevant tests and tasks（完成相关测试和任务）

**Comment by tobehardest** [comment] 2023-03-30 16:06
I want to try it, can you assign it to me？

**Comment by chickenlj** [comment] 2023-04-07 13:07
duplicate of #2284

**Closed** 2023-04-07 13:12 UTC
