### ISSUE TITLE
Give the support of grpc/http2

### ISSUE THREAD

**Issue by XiaoYaoheihei** [apache/dubbo-go#2266] opened 2023-03-25 12:13 UTC
- grpc/http2 的支持情况（支持程度、易用性 grec-web/curl）

- grpc/http2 support (degree of support, ease of use grec-web/curl)

**Comment by chickenlj** [comment] 2023-03-27 00:30
Duplicate of #2263

**Closed** 2023-03-27 00:31 UTC
